---
spring:
  application:
    name: ${EUREKA_NAME}

eureka:
  instance:
    hostname: ${EUREKA_NAME}
 registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

